repos:
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
          - id: pyupgrade
            args: ["--py36-plus"]
    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
          - id: black
            language_version: python3.9
    - repo: https://github.com/phantomcyber/dev-cicd-tools
      rev: v1.16
      hooks:
          - id: org-hook
          - id: package-app-dependencies
    - repo: https://github.com/Yelp/detect-secrets
      rev: v1.4.0
      hooks:
          - id: detect-secrets
            args: ["--no-verify", "--exclude-files", "^censys.json$"]
